/**
 * Edge fallback for wiki.p2pfoundation.net
 *
 * WHY THIS EXISTS
 * ---------------
 * 2026-08-17: the Netcup host went off the network at layer 3 and every public
 * site on it went with it. Readers of the wiki got a raw Cloudflare 530 /
 * "error code: 1033" screen for hours. The wiki itself was fine; its origin was
 * simply gone, and nothing at the edge was prepared to say so.
 *
 * A Worker runs at the edge regardless of origin health, which is the whole
 * point — it does not care which error class the origin produced, or whether the
 * origin exists at all.
 *
 * WHY NOT "ALWAYS ONLINE"
 * -----------------------
 * Cloudflare's free Always Online toggle looks like it solves this and does not:
 * it "only activates when Cloudflare cannot connect to your origin at all
 * (resulting in Cloudflare-generated 520-527 status codes)". The wiki is behind
 * a Cloudflare Tunnel, and a tunnel with no connector produces 530/1033 — outside
 * that range. It would not have fired on 2026-08-17.
 *
 * FALLBACK ORDER, and why it is this order
 * ----------------------------------------
 *   1. origin                — always tried first; a healthy origin is untouched
 *   2. R2 snapshot (ours)    — no third-party dependency, always available
 *   3. Wayback Machine       — opportunistic only
 *   4. branded offline page  — always works, needs nothing
 *
 * The Archive sits BELOW our own snapshot deliberately. On 2026-08-17, while this
 * was being written, web.archive.org was itself returning 503 "Internet Archive
 * services are temporarily offline" — during the very outage it was meant to
 * cover. A fallback whose availability you do not control is a nice-to-have, not
 * a plan.
 *
 * SAFETY
 * ------
 * This Worker sits in front of a healthy origin 99% of the time, so its failure
 * mode matters more than its feature set. Every path is wrapped: any unexpected
 * error falls through to a plain origin fetch, and FALLBACK_ENABLED="off" makes
 * it a transparent pass-through without a redeploy.
 */

import { renderWikitext, pathToTitle, escapeHtml } from "./wikitext.js";

/**
 * Cloudflare-generated codes meaning "could not reach the origin at all".
 * 530 is the tunnel-down case (1033) that started all this.
 *
 * 502/503/504 are deliberately NOT here. Those can come from Traefik or from
 * MediaWiki itself, and a Traefik that answers is a host that is up — a
 * different failure, wanting a different response. Serving a two-week-old
 * snapshot over a transient application hiccup would be a downgrade.
 */
const ORIGIN_FAILURE_STATUSES = new Set([520, 521, 522, 523, 524, 525, 526, 527, 530]);

export function isOriginFailure(status) {
  return ORIGIN_FAILURE_STATUSES.has(status);
}

/** Paths that cannot possibly be served from a static snapshot. */
export function isDynamicPath(pathname, search) {
  const p = pathname.toLowerCase();
  if (p.startsWith("/special:")) return true;
  if (p.startsWith("/index.php")) return true;
  if (p.startsWith("/api.php") || p.startsWith("/rest.php")) return true;
  if (p.startsWith("/load.php")) return true;
  if (/[?&]action=(edit|submit|history|raw)/i.test(search || "")) return true;
  return false;
}

/**
 * Requests for a subresource rather than a document. These must never receive
 * the HTML offline page: a stylesheet request answered with a full HTML
 * document is not a friendlier error, it is a broken stylesheet, and the same
 * body would be handed back for every missing image on the page.
 */
const ASSET_EXTENSIONS =
  /\.(png|jpe?g|gif|webp|avif|svg|ico|css|js|mjs|json|woff2?|ttf|eot|map|pdf|zip|gz|bz2|tar|xml)$/i;

export function isAssetPath(pathname) {
  return ASSET_EXTENSIONS.test(pathname) || pathname.toLowerCase().startsWith("/images/");
}

const CACHE_TTL_SECONDS = 600;

/**
 * Wiki title -> R2 object key. MUST stay byte-identical to `safe_key()` in
 * scripts/build-snapshot.py. If the two ever drift, every lookup misses and the
 * fallback degrades to the generic offline page without erroring — a silent
 * failure, so it is asserted in test/fallback.test.mjs against a fixture list
 * generated by the Python side.
 *
 * Not encodeURIComponent: it and Python's quote() disagree on !'()*, and wiki
 * titles are full of parentheses.
 */
export function snapshotKey(title) {
  const normalised = title.normalize("NFC").trim().replace(/\s+/g, "_");
  return `pages/${normalised.replace(/%/g, "%25").replace(/\//g, "%2F")}`;
}

export default {
  async fetch(request, env, ctx) {
    if ((env.FALLBACK_ENABLED || "on").toLowerCase() === "off") {
      return fetch(request);
    }

    let originResponse = null;
    let originThrew = false;

    try {
      originResponse = await fetch(request);
    } catch {
      originThrew = true;
    }

    if (originResponse && !isOriginFailure(originResponse.status)) {
      return originResponse;
    }

    // Origin is unreachable from here on.
    try {
      return await serveFallback(request, env, ctx, {
        originStatus: originThrew ? null : originResponse.status,
      });
    } catch (err) {
      // A bug in the fallback must never be worse than the outage it covers.
      if (originResponse) return originResponse;
      return offlineResponse(request, env, {
        detail: `fallback error: ${err && err.message ? err.message : "unknown"}`,
      });
    }
  },
};

async function serveFallback(request, env, ctx, meta) {
  const url = new URL(request.url);
  const method = request.method.toUpperCase();

  // Never replay a write against a fallback. An edit that appears to succeed
  // and is silently discarded is far worse than a clear refusal.
  if (method !== "GET" && method !== "HEAD") {
    return offlineResponse(request, env, {
      ...meta,
      writeAttempt: true,
      status: 503,
    });
  }

  const cache = caches.default;
  // Namespaced key so a cached fallback can never be mistaken for a cached
  // origin response once the origin recovers.
  const cacheKey = new Request(
    `https://fallback.p2pwiki.internal${url.pathname}${url.search}`,
    { method: "GET" }
  );

  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  const asset = isAssetPath(url.pathname);
  let response = null;

  if (!isDynamicPath(url.pathname, url.search)) {
    // The snapshot holds article wikitext only, so an asset never has a hit
    // there — skipping it saves an R2 read on every image of every page.
    if (!asset) response = await fromSnapshot(url, env, meta);
    if (!response && (env.WAYBACK_ENABLED || "on").toLowerCase() !== "off") {
      response = await fromWayback(url, env, meta);
    }
  }

  if (!response) {
    response = asset ? assetUnavailable() : offlineResponse(request, env, meta);
  }

  if (response.status !== 503 || response.headers.get("x-p2pwiki-fallback")) {
    ctx.waitUntil(cache.put(cacheKey, response.clone()));
  }
  return response;
}

/**
 * Our own snapshot, built from the weekly MediaWiki XML dump.
 * Keys are the wiki title with spaces as underscores — the same normalisation
 * MediaWiki applies to URLs — so lookup is a direct GET with no manifest.
 */
async function fromSnapshot(url, env, meta) {
  if (!env.SNAPSHOT) return null;

  const title = pathToTitle(url.pathname);
  const object = await env.SNAPSHOT.get(snapshotKey(title));
  if (!object) return null;

  const wikitext = await object.text();
  const builtAt = (object.customMetadata && object.customMetadata.builtAt) || env.SNAPSHOT_BUILT || "unknown date";

  const body = pageShell({
    title,
    builtAt,
    source: "snapshot",
    meta,
    content: renderWikitext(wikitext, title),
  });

  return new Response(body, {
    // 503 + Retry-After on the HTML document is the standards-correct signal for
    // planned-to-return downtime, and it stops search engines treating a reduced
    // offline copy as the canonical page.
    status: 503,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "retry-after": "3600",
      "x-p2pwiki-fallback": "snapshot",
    },
  });
}

/** Opportunistic. Never fails the request — returns null and lets the chain continue. */
async function fromWayback(url, env, meta) {
  const target = `https://web.archive.org/web/2id_/${url.toString()}`;
  let archived;
  try {
    archived = await fetch(target, {
      redirect: "follow",
      cf: { cacheTtl: CACHE_TTL_SECONDS, cacheEverything: true },
    });
  } catch {
    return null;
  }
  if (!archived.ok) return null;

  const type = archived.headers.get("content-type") || "";
  if (!type.includes("text/html")) {
    // Assets (CSS, images) are served straight through with 200 so the browser
    // actually applies them — only the HTML document carries the 503 signal.
    return new Response(archived.body, {
      status: 200,
      headers: {
        "content-type": type || "application/octet-stream",
        "cache-control": "no-store",
        "x-p2pwiki-fallback": "wayback-asset",
      },
    });
  }

  const html = await archived.text();
  const banner = bannerHtml({
    source: "wayback",
    builtAt: "the Internet Archive",
    meta,
  });
  const injected = html.replace(/<body([^>]*)>/i, `<body$1>${banner}`);

  return new Response(injected, {
    status: 503,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "retry-after": "3600",
      "x-p2pwiki-fallback": "wayback",
    },
  });
}

/** Short, correctly-typed nothing. A broken image beats an HTML page in an <img>. */
function assetUnavailable() {
  return new Response("", {
    status: 503,
    headers: {
      "cache-control": "no-store",
      "retry-after": "1800",
      "x-p2pwiki-fallback": "asset-unavailable",
    },
  });
}

function bannerHtml({ source, builtAt, meta }) {
  const where =
    source === "wayback"
      ? "an Internet Archive copy"
      : `an offline copy taken ${escapeHtml(builtAt)}`;
  const code = meta && meta.originStatus ? ` (origin returned ${meta.originStatus})` : "";
  return `<div class="p2pwiki-offline-banner" role="status">
  <strong>The P2P Foundation Wiki is temporarily offline.</strong>
  You are reading ${where}${escapeHtml(code)}. Editing, search and login are unavailable
  until the server is back. Content may be out of date.
</div>`;
}

function pageShell({ title, builtAt, source, meta, content }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<title>${escapeHtml(title)} — P2P Foundation Wiki (offline copy)</title>
${STYLE}
</head>
<body>
${bannerHtml({ source, builtAt, meta })}
<main>
<h1>${escapeHtml(title)}</h1>
${content}
</main>
<footer>
  <p>Offline copy served from the edge. Content is licensed
  <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>.</p>
</footer>
</body>
</html>`;
}

function offlineResponse(request, env, meta) {
  const url = new URL(request.url);
  const title = pathToTitle(url.pathname);
  const writeAttempt = meta && meta.writeAttempt;

  const body = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<title>P2P Foundation Wiki — temporarily offline</title>
${STYLE}
</head>
<body>
<main>
<h1>The P2P Foundation Wiki is temporarily offline</h1>
<p>The server hosting the wiki is currently unreachable. This is a temporary
outage, not a change to the wiki — nothing has been lost, and the site will
return.</p>
${
  writeAttempt
    ? `<p><strong>Your edit was not saved.</strong> Editing is unavailable while the
server is down. Copy your text somewhere safe and submit it again once the wiki
is back — nothing you typed has been sent anywhere.</p>`
    : `<p>We could not find an offline copy of
<code>${escapeHtml(title)}</code> to show you.</p>`
}
<h2>In the meantime</h2>
<ul>
  <li>Full wiki exports (XML dumps and images) are published at
      <a href="https://wiki.p2pfoundation.net/dumps/">/dumps/</a> when the site is up.</li>
  <li>Archived copies of most pages exist at the
      <a href="https://web.archive.org/web/*/wiki.p2pfoundation.net/*">Internet Archive</a>.</li>
  <li>The P2P Foundation blog is at
      <a href="https://blog.p2pfoundation.net/">blog.p2pfoundation.net</a>.</li>
</ul>
${meta && meta.detail ? `<p class="detail">${escapeHtml(meta.detail)}</p>` : ""}
</main>
<footer>
  <p>Content is licensed
  <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>.</p>
</footer>
</body>
</html>`;

  return new Response(body, {
    status: (meta && meta.status) || 503,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "retry-after": "1800",
      "x-p2pwiki-fallback": "offline-page",
    },
  });
}

const STYLE = `<style>
:root{
  --bg:#fdfdfb; --fg:#1c1c1a; --muted:#5d5d57; --rule:#e0dfd8;
  --accent:#8a5a2b; --banner-bg:#fdf3e3; --banner-fg:#5c3d13; --banner-rule:#e0c48a;
}
@media (prefers-color-scheme: dark){
  :root{
    --bg:#16161a; --fg:#e8e6e1; --muted:#a3a099; --rule:#31313a;
    --accent:#d7a76a; --banner-bg:#2a2216; --banner-fg:#f0d9ae; --banner-rule:#6b5326;
  }
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
  font:16px/1.65 Georgia,"Iowan Old Style",serif;}
main,footer{max-width:44rem;margin:0 auto;padding:0 1.25rem}
main{padding-top:2rem;padding-bottom:3rem}
h1{font-size:1.9rem;line-height:1.2;margin:0 0 1rem}
h2,h3,h4,h5,h6{line-height:1.25;margin:2rem 0 .6rem}
h2{font-size:1.35rem}h3{font-size:1.15rem}
p{margin:0 0 1rem}
a{color:var(--accent)}
ul,ol{margin:0 0 1rem;padding-left:1.4rem}
li{margin:.25rem 0}
blockquote{margin:0 0 1rem;padding-left:1rem;border-left:3px solid var(--rule);color:var(--muted)}
hr{border:0;border-top:1px solid var(--rule);margin:2rem 0}
code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.9em;
  background:color-mix(in srgb,var(--fg) 8%,transparent);padding:.1em .35em;border-radius:3px}
.omitted,.detail{color:var(--muted);font-style:italic;font-size:.9rem}
footer{border-top:1px solid var(--rule);padding-top:1rem;padding-bottom:2rem;
  color:var(--muted);font-size:.85rem}
.p2pwiki-offline-banner{
  background:var(--banner-bg);color:var(--banner-fg);
  border-bottom:1px solid var(--banner-rule);
  padding:.85rem 1.25rem;font:15px/1.5 system-ui,-apple-system,sans-serif;
  position:sticky;top:0;z-index:9999;
}
.p2pwiki-offline-banner strong{display:block;margin-bottom:.15rem}
</style>`;
